### ISSUE TITLE
Mettre une image

### ISSUE THREAD

**Issue by MilanMM** [lycee-chaptal-sii/jules-alice-anto-milan#1]
Bonjour,
J'aimerai savoir comment intégrer une image sur Github pour pouvoir ajouter un lien qui mène à celle-ci dans le code ( Partie Communiquer ). @atrantan

**Comment by atrantan** [comment]
@MilanMM Ajoute ton fichier image (ex: toto.jpg) dans le dossier docs du projet. Puis pour l'ajouter sur ta page écrit `![mon_image](toto.jpg)` là où tu veux le faire apparaître. N'oublie pas d'ajouter ton fichier image en faisant la validation et pousse la validation comme d'habitude.
